# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from upload_thing_python_sdk.type.file_mark_for_deletion_request_custom_ids import FileMarkForDeletionRequestCustomIds
from upload_thing_python_sdk.type.file_mark_for_deletion_request_file_keys import FileMarkForDeletionRequestFileKeys
from upload_thing_python_sdk.type.file_mark_for_deletion_request_files import FileMarkForDeletionRequestFiles

class RequiredFileMarkForDeletionRequest(TypedDict):
    pass

class OptionalFileMarkForDeletionRequest(TypedDict, total=False):
    files: FileMarkForDeletionRequestFiles

    fileKeys: FileMarkForDeletionRequestFileKeys

    customIds: FileMarkForDeletionRequestCustomIds

class FileMarkForDeletionRequest(RequiredFileMarkForDeletionRequest, OptionalFileMarkForDeletionRequest):
    pass
