# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from upload_thing_python_sdk import UploadThing

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        uploadthing = UploadThing(
        
                        api_key_auth = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(uploadthing)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
