# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

import unittest

import upload_thing_python_sdk
from upload_thing_python_sdk.model.callback_mark_upload_failed_request import CallbackMarkUploadFailedRequest
from upload_thing_python_sdk import configuration


class TestCallbackMarkUploadFailedRequest(unittest.TestCase):
    """CallbackMarkUploadFailedRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
