# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

import unittest

import upload_thing_python_sdk
from upload_thing_python_sdk.model.file_request_presigned_url404_response import FileRequestPresignedUrl404Response
from upload_thing_python_sdk import configuration


class TestFileRequestPresignedUrl404Response(unittest.TestCase):
    """FileRequestPresignedUrl404Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
