# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from upload_thing_python_sdk.pydantic.file_mark_for_deletion_request_custom_ids import FileMarkForDeletionRequestCustomIds
from upload_thing_python_sdk.pydantic.file_mark_for_deletion_request_file_keys import FileMarkForDeletionRequestFileKeys
from upload_thing_python_sdk.pydantic.file_mark_for_deletion_request_files import FileMarkForDeletionRequestFiles

class FileMarkForDeletionRequest(BaseModel):
    files: typing.Optional[FileMarkForDeletionRequestFiles] = Field(None, alias='files')

    file_keys: typing.Optional[FileMarkForDeletionRequestFileKeys] = Field(None, alias='fileKeys')

    custom_ids: typing.Optional[FileMarkForDeletionRequestCustomIds] = Field(None, alias='customIds')
    class Config:
        arbitrary_types_allowed = True
