# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from upload_thing_python_sdk.pydantic.multipart_upload_urls_urls import MultipartUploadURLsUrls

class MultipartUploadURLs(BaseModel):
    key: str = Field(alias='key')

    file_name: str = Field(alias='fileName')

    file_type: str = Field(alias='fileType')

    file_url: str = Field(alias='fileUrl')

    content_disposition: Literal["inline", "attachment"] = Field(alias='ContentDisposition')

    polling_jwt: str = Field(alias='pollingJwt')

    polling_url: str = Field(alias='pollingUrl')

    custom_id: typing.Optional[str] = Field(alias='customId')

    urls: MultipartUploadURLsUrls = Field(alias='urls')

    upload_id: str = Field(alias='uploadId')

    chunk_size: typing.Union[int, float] = Field(alias='chunkSize')

    chunk_count: typing.Union[int, float] = Field(alias='chunkCount')
    class Config:
        arbitrary_types_allowed = True
