# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from upload_thing_python_sdk.paths.failure_callback.post import MarkUploadFailed
from upload_thing_python_sdk.apis.tags.callback_api_raw import CallbackApiRaw


class CallbackApi(
    MarkUploadFailed,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CallbackApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CallbackApiRaw(api_client)
