# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from upload_thing_python_sdk.paths.get_file_url.post import GetFileUrls
from upload_thing_python_sdk.paths.list_files.post import ListFiles
from upload_thing_python_sdk.paths.delete_file.post import MarkForDeletion
from upload_thing_python_sdk.paths.rename_files.post import RenameFiles
from upload_thing_python_sdk.paths.request_file_access.post import RequestPresignedUrl
from upload_thing_python_sdk.paths.upload_files.post import RequestPresignedUrls
from upload_thing_python_sdk.paths.rename_file.post import UpdateFileName
from upload_thing_python_sdk.apis.tags.file_api_raw import FileApiRaw


class FileApi(
    GetFileUrls,
    ListFiles,
    MarkForDeletion,
    RenameFiles,
    RequestPresignedUrl,
    RequestPresignedUrls,
    UpdateFileName,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: FileApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = FileApiRaw(api_client)
