# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from upload_thing_python_sdk.paths.get_file_url.post import GetFileUrlsRaw
from upload_thing_python_sdk.paths.list_files.post import ListFilesRaw
from upload_thing_python_sdk.paths.delete_file.post import MarkForDeletionRaw
from upload_thing_python_sdk.paths.rename_files.post import RenameFilesRaw
from upload_thing_python_sdk.paths.request_file_access.post import RequestPresignedUrlRaw
from upload_thing_python_sdk.paths.upload_files.post import RequestPresignedUrlsRaw
from upload_thing_python_sdk.paths.rename_file.post import UpdateFileNameRaw


class FileApiRaw(
    GetFileUrlsRaw,
    ListFilesRaw,
    MarkForDeletionRaw,
    RenameFilesRaw,
    RequestPresignedUrlRaw,
    RequestPresignedUrlsRaw,
    UpdateFileNameRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
