# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from upload_thing_python_sdk.paths.server_callback.get import GetData
from upload_thing_python_sdk.paths.server_callback.post import SetData
from upload_thing_python_sdk.apis.tags.server_callback_api_raw import ServerCallbackApiRaw


class ServerCallbackApi(
    GetData,
    SetData,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ServerCallbackApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ServerCallbackApiRaw(api_client)
