# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from upload_thing_python_sdk.paths.prepare_upload.post import RequestPresignedUrls
from upload_thing_python_sdk.apis.tags.upload_api_raw import UploadApiRaw


class UploadApi(
    RequestPresignedUrls,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UploadApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UploadApiRaw(api_client)
