# coding: utf-8

# flake8: noqa

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

__version__ = "6.4.0"

# import ApiClient
from upload_thing_python_sdk.api_client import ApiClient

# import Configuration
from upload_thing_python_sdk.configuration import Configuration

# import exceptions
from upload_thing_python_sdk.exceptions import OpenApiException
from upload_thing_python_sdk.exceptions import ApiAttributeError
from upload_thing_python_sdk.exceptions import ApiTypeError
from upload_thing_python_sdk.exceptions import ApiValueError
from upload_thing_python_sdk.exceptions import ApiKeyError
from upload_thing_python_sdk.exceptions import ApiException

from upload_thing_python_sdk.client import UploadThing
