# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from upload_thing_python_sdk import schemas  # noqa: F401


class FileRequestPresignedUrlsRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "contentDisposition",
            "files",
        }
        
        class properties:
        
            @staticmethod
            def files() -> typing.Type['FileRequestPresignedUrlsRequestFiles']:
                return FileRequestPresignedUrlsRequestFiles
            
            
            class contentDisposition(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def INLINE(cls):
                    return cls("inline")
                
                @schemas.classproperty
                def ATTACHMENT(cls):
                    return cls("attachment")
            
            
            class acl(
                schemas.EnumBase,
                schemas.StrSchema
            ):
                
                @schemas.classproperty
                def PUBLICREAD(cls):
                    return cls("public-read")
                
                @schemas.classproperty
                def PRIVATE(cls):
                    return cls("private")
            metadata = schemas.AnyTypeSchema
            __annotations__ = {
                "files": files,
                "contentDisposition": contentDisposition,
                "acl": acl,
                "metadata": metadata,
            }
    
    contentDisposition: MetaOapg.properties.contentDisposition
    files: 'FileRequestPresignedUrlsRequestFiles'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["files"]) -> 'FileRequestPresignedUrlsRequestFiles': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["contentDisposition"]) -> MetaOapg.properties.contentDisposition: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["acl"]) -> MetaOapg.properties.acl: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> MetaOapg.properties.metadata: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["files", "contentDisposition", "acl", "metadata", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["files"]) -> 'FileRequestPresignedUrlsRequestFiles': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["contentDisposition"]) -> MetaOapg.properties.contentDisposition: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["acl"]) -> typing.Union[MetaOapg.properties.acl, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union[MetaOapg.properties.metadata, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["files", "contentDisposition", "acl", "metadata", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        contentDisposition: typing.Union[MetaOapg.properties.contentDisposition, str, ],
        files: 'FileRequestPresignedUrlsRequestFiles',
        acl: typing.Union[MetaOapg.properties.acl, str, schemas.Unset] = schemas.unset,
        metadata: typing.Union[MetaOapg.properties.metadata, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'FileRequestPresignedUrlsRequest':
        return super().__new__(
            cls,
            *args,
            contentDisposition=contentDisposition,
            files=files,
            acl=acl,
            metadata=metadata,
            _configuration=_configuration,
            **kwargs,
        )

from upload_thing_python_sdk.model.file_request_presigned_urls_request_files import FileRequestPresignedUrlsRequestFiles
