# coding: utf-8

"""
    UploadThing REST API

    UploadThing is the easiest way to add file uploads to your full stack TypeScript application. Many services have tried to build a \"better S3\", but in our opinion, none found the right compromise of ownership, flexibility and safety.

    The version of the OpenAPI document: 6.4.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from upload_thing_python_sdk import schemas  # noqa: F401


class MultipartCompleteUploadRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "uploadId",
            "fileKey",
            "etags",
        }
        
        class properties:
            fileKey = schemas.StrSchema
            uploadId = schemas.StrSchema
        
            @staticmethod
            def etags() -> typing.Type['MultipartCompleteUploadRequestEtags']:
                return MultipartCompleteUploadRequestEtags
            __annotations__ = {
                "fileKey": fileKey,
                "uploadId": uploadId,
                "etags": etags,
            }
    
    uploadId: MetaOapg.properties.uploadId
    fileKey: MetaOapg.properties.fileKey
    etags: 'MultipartCompleteUploadRequestEtags'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fileKey"]) -> MetaOapg.properties.fileKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["uploadId"]) -> MetaOapg.properties.uploadId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["etags"]) -> 'MultipartCompleteUploadRequestEtags': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["fileKey", "uploadId", "etags", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fileKey"]) -> MetaOapg.properties.fileKey: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["uploadId"]) -> MetaOapg.properties.uploadId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["etags"]) -> 'MultipartCompleteUploadRequestEtags': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["fileKey", "uploadId", "etags", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        uploadId: typing.Union[MetaOapg.properties.uploadId, str, ],
        fileKey: typing.Union[MetaOapg.properties.fileKey, str, ],
        etags: 'MultipartCompleteUploadRequestEtags',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MultipartCompleteUploadRequest':
        return super().__new__(
            cls,
            *args,
            uploadId=uploadId,
            fileKey=fileKey,
            etags=etags,
            _configuration=_configuration,
            **kwargs,
        )

from upload_thing_python_sdk.model.multipart_complete_upload_request_etags import MultipartCompleteUploadRequestEtags
